name: Linux

on:
  repository_dispatch:
    types: [create-pull-request]
  pull_request:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install mesa-common-dev clang libsdl2-2.0-0 libsdl2-dev build-essential libvulkan-dev

    - name: Build
      run: cd sandbox && make
