name: MacOS

on:
  repository_dispatch:
    types: [create-pull-request]
  pull_request:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install system dependencies
      run: brew install SDL2 vulkan-headers

    - name: Build
      run: cd sandbox && make
